services:
  agroapi:
    build: .
    image: backagri
    command: npx nodemon app.js
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "backend_user"
      DB_PASS: "pass1234"
      DB_NAME: "agro_db"
    volumes:
      - ./app:/app
      - /app/node_modules

  db:
    image: postgres:18
    ports:
      - "5433:5432"
    environment: #info de base de datos
      POSTGRES_USER: "backend_user" 
      POSTGRES_PASSWORD: "pass1234"
      POSTGRES_DB: "agro_db" 
    volumes:
      - ./data:/var/lib/postgresql #Guarda los datos en la carpeta data/ que se te crea en /backend/data
      - ./app/db/schemas.sql:/docker-entrypoint-initdb.d/1-schemas.sql:ro #agarra lo que esta adentro de schemas.sql y lo carga
      - ./app/db/seeds.sql:/docker-entrypoint-initdb.d/2-seeds.sql:ro #INYECTA datos a la base de schemas.sql